# Docker-compose.yml

version: '3'

# left      right
# container:host

# networks:
#    backend

services:
    node:
        build: .
        container_name: node
        volumes:
            - ./assets:/usr/src/app/assets
            - ./views:/usr/src/app/views
            - ./src:/usr/src/app/src
        ports:
            - "80:3000"
        environment: 
            - "MONGO_CONNECTION_STR=mongodb://root:MongoDB2019!@mongo:27017/?authSource=admin&readPreference=primary&appname=MongoDB%20Compass&ssl=false"
        links:
            - mongo
        networks:
            - mongo-network
        
    mongo:
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: MongoDB2019!
        ports:
            - "27017:27017"
        networks:
            - mongo-network
networks: 
    mongo-network:
        driver: bridge